import { initReactI18next } from "react-i18next";
import i18n from "i18next";

i18n.use(initReactI18next).init({
  lng: "",
  resources: {
    en: {
      translation: {
        "Sign Up": "Sign Up",
        "Sign in": "Sign in",
        "Az Name": "Az Name",
        "Name": "Name",
        "Email": "Email",
        "Password": "Password",
        "I agree to AcreTrader's": "I agree to AcreTrader's",
        "If you have an account": "If you have an account",
        "Privacy Policy": "Privacy Policy",
        "Login": "Login",
        "Log in": "Login",
        "Login Your Account": "Login Your Account",
        "Get Started": "Get Started",
        "Subscribe to Lay of the Land Newsletter": "Subscribe to Lay of the Land Newsletter",
        "Subscribe": "Subscribe",
        "Recently Funded Investments": "Recently Funded Investments",
        "Fully subscribed investments that are in active operation and generating applicable distributions.": "Fully subscribed investments that are in active operation and generating applicable distributions.",
        "Why GreenInvest.az?": "Why GreenInvest.az?",
        "Learning-center": "Learning-center",
        "Visit Why Farmland": "Visit Why Farmland",
        "Invest Now": "Invest Now",
        "Calculate your Investment": "Calculate your Investment",
        "If you have don't have an account": "If you have don't have an account",
        "Terms of Use": "Terms of Use",
        "Download Document": "Download Document",

        "Contact AcreTrader": "Contact AcreTrader",
        "Our team is available to answer any questions you may have": "Our team is available to answer any questions you may have",
        "Contact Information": "Contact Information",
        "Message": "Message",
        "Follow Us": "Follow Us",

        "Full Name": "Full Name",
        "Your name may appear around here where you are mentioned. You can change or remove it at any time": "our name may appear around here where you are mentioned. You can change or remove it at any time",
        "ACCOUNT SETTINGS": "ACCOUNT SETTINGS",
        "SECURITY SETTINGS": "SECURITY SETTINGS",
     





        "About": "About",
        "Why GreenInvest": "Why GreenInvest",
        "Contact us": "Contact us",
        "Investment": "Investment",
        "Properties": "Properties",
        "Portfolio": "Portfolio",
        "Property": "Property",
        "Blog": "Blog",
        "For-Farmers": "For-Farmers",
        "Learning-Center": "Learning-Center",
        "View All": "View All",
        "Notifications": "Notifications",
        "Unread Notifications": "Unread Notifications",
        "Login": "Login",
        "Logout": "Logout",
        "Home": "Home",
        "Row Crop": "Row Crop",
        "Farm Price": "Row Crop",
        "Total Acres": "Total Acres",
        "Price/Ac": "Price/Ac",
        "EsL. Ownership Duration": "EsL. Ownership Duration",
        "Investment Type": "Investment Type",
        "Investment In Amount": "Investment In Amount",
        "Investment In Hectare": "Investment In Hectare",
        "User Avg Forecasted Productivity": "User Avg Forecasted Productivity",
        "User Forecasted Profit": "User Forecasted Profit",
        "Description": "Description",
        "Subscribed": "Subscribed",
        "Min.Investment": "Min.Investment",
        "Full Name": "Full Name",
        "Phone Number": "Phone Number",
        "Submit": "Submit",
        "Documents": "Documents",
        "Financials": "Financials",
        "Overview": "Overview",
        "Maps": "Maps",
        "Property Size": "Property Size",
        "Property Price": "Property Price",
        "Productivity": "Productivity",
        "Price Per Unit": "Price Per Unit",
        "Profit": "Profit",
        "Risk Level": "Risk Level",
        "Total Forecasted Productivity": "Total Forecasted Productivity",
        "Total Forecasted Earn Amount": "Total Forecasted Earn Amount",
        "Project Starting Date": "Project Starting Date",
        "Project End Date": "Project End Date",
        "Investment Starting Date": "Investment Starting Date",
        "Investment End Date": "Investment End Date",
        "Minimum Investment": "Minimum Investment",
        "Maximum Investment": "Maximum Investment",
        "Number Of Tillable Acres": "Number Of Tillable Acres",
        "Total Cost Per Acre" : "Total Cost Per Acre",
        "Wind Lease Income": "Wind Lease Income",
        "Total Acres Info": "Total Acres Info",
        "User Profile Setting": "User Profile Setting",
        "Please, Provide us with your Contact Information": "Please, Provide us with your Contact Information"
      }
    },

    az: {
      translation: {
        "Sign Up": "Abunə olun",
        "Sign in": "Giriş",
        "Az Name": "Az Ad",
        "Name":"Ad",
        "Email": "E-poçt",
        "Password": "Parol",
        "I agree to GreenInvest": "Mən GreenInvest ilə razıyam",
        "If you have an account":"Hesabınız varsa",
        "Privacy Policy": "Məxfilik Siyasəti",
        "Log in": "Giriş",
        "Login": "Giriş",
        "Login Your Account": "Hesabınıza daxil olun",
        "Get Started": "Get Started",
        "Subscribe to Lay of the Land Newsletter": "Lay of the Land bülleteninə abunə olun",
        "Subscribe": "Subscribe",
        "Recently Funded Investments": "Son vaxtlarda maliyyələşdirilən investisiyalar",
        "Fully subscribed investments that are in active operation and generating applicable distributions.": "Fəal əməliyyatda olan və müvafiq paylamalar yaradan tam abunə edilmiş investisiyalar.",
        "Learning-center": "Tədris mərkəzi",
        "Visit Why Farmland": "Niyə əkin sahələrini ziyarət et",
        "Invest Now": "İndi investisiya et",
        "Calculate your Investment": "İnvestisiyanızı hesablayın",
        "If you have don't have an account": "Əgər hesabınız yoxdursa",
        "Terms of Use": "Əgər hesabınız yoxdursa",
        "Download Document": "Sənədi Yükləyin",
        "YOUR PROFILE INFORMATION": "SİZİN PROFİL MƏLUMATINIZ",
        "Full Name": "Tam adı",
        "Your name may appear around here where you are mentioned. You can change or remove it at any time": "Sizin adınız qeyd olunduğunuz yerdə görünə bilər. İstənilən vaxt onu dəyişə və ya silə bilərsiniz",
        "ACCOUNT SETTINGS": "HESAB TƏNZİMLƏMƏLƏRİ",
        "SECURITY SETTINGS": "TƏHLÜKƏSİZLİK PARAMETRELƏRİ",

        "Contact AcreTrader": "Contact AcreTrader",
        "Our team is available to answer any questions you may have": "Komandamız sizi maraqlandıran bütün suallara cavab verməyə hazırdır",
        "Contact Information": "Əlaqə məlumatı",
        "Message": "Mesaj",
        "Follow Us": "Bizi izləyin",

        "About": "Haqqında",
        "Why GreenInvest": "Niyə GreenInvest",
        "Contact us": "Bizimlə əlaqə saxlayın",
        "Investment": "İnvestisiya",
        "Properties": "Xüsusiyyətlər",
        "Portfolio": "Portfolio",
        "Property": "Əmlak",
        "Blog": "Hola",
        "For-Farmers": "Fermerlər üçün",
        "Learning-Center": "Tədris Mərkəzi",
        "View All": "Hamısına Bax",
        "Notifications": "Bildirişlər",
        "Unread Notifications": "Unread Bildirişlər",
        "Login": "Daxil ol",
        "Logout": "Çıxış",
        "Home": "ev",
        "Row Crop": "Sıra Bitki",
        "Farm Price": "Ferma qiyməti",
        "Total Acres": "Ümumi hektar",
        "Price/Ac": "Qiymət/Ac",
        "EsL. Ownership Duration": "EsL. Mülkiyyət müddəti",
        "Investment Type": "İnvestisiya növü",
        "Investment In Amount": "Məbləğdə İnvestisiya",
        "Investment In Hectare": "Hektar İnvestisiya",
        "User Avg Forecasted Productivity": "İstifadəçi Ort. Proqnozlaşdırılan Məhsuldarlıq",
        "User Forecasted Profit": "İstifadəçinin proqnozlaşdırılan mənfəəti",
        "Description": "Təsvir",
        "Subscribed": "Abunə oldu",
        "Min.Investment": "Min.İnvestisiya",
        "Full Name": "Tam adı",
        "Phone Number": "Telefon nömrəsi",
        "Submit": "təqdim",
        "Documents": "Sənədlər",
        "Financials": "Maliyyə",
        "Overview": "Ümumi baxış",
        "Maps": "Xəritələr",
        "Property Size": "Property Size",
        "Property Price": "Property Price",
        "Productivity": "Productivity",
        "Price Per Unit": "Price Per Unit",
        "Profit": "Profit",
        "Risk Level": "Risk Level",
        "Total Forecasted Productivity": "Total Forecasted Productivity",
        "Total Forecasted Earn Amount": "Total Forecasted Earn Amount",
        "Project Starting Date": "Project Starting Date",
        "Project End Date": "Project End Date",
        "Investment Starting Date": "Investment Starting Date",
        "Investment End Date": "Investment End Date",
        "Minimum Investment": "Minimum Investment",
        "Maximum Investment": "Maximum Investment",
        "Number Of Tillable Acres": "Number Of Tillable Acres",
        "Total Cost Per Acre" : "Total Cost Per Acre",
        "Wind Lease Income": "Wind Lease Income",
        "Total Acres Info": "Total Acres Info",


        "User Profile Setting": "İstifadəçi Profili Parametrləri",
        "Please, Provide us with your Contact Information":"Zəhmət olmasa, Əlaqə məlumatlarınızı bizə təqdim edin"

      }
    },
  },
  keySeparator: false,
  interpolation: { escapeValue: false }
});

export default i18n;
